version: 2.1

jobs:
  waste_time:
    docker:
      - image: cimg/base:2023.09
    resource_class: small
    steps:
      - checkout
      - run:
          name: Cancel redundant runs
          command: scripts/auto-cancel-redundant.sh
      - run:
          name: Sleep for five minutes
          command: sleep 300

workflows:
  version: 2
  meditative_flow:
    jobs:
      - waste_time
